//go:build embed

package web

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	htmlpkg "html"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/gin-gonic/gin"
)

const (
	// NonceHTMLPlaceholder is the placeholder for nonce in HTML script tags
	NonceHTMLPlaceholder  = "__CSP_NONCE_VALUE__"
	frontendNoIndexValue  = "noindex, nofollow, noarchive"
	seoSiteOrigin         = "https://myrt.cc"
	seoShareImageURL      = seoSiteOrigin + "/og-image.png"
	seoDefaultSiteName    = "模驿"
	seoDefaultDescription = "模驿提供 Claude、GPT、Gemini 等主流模型的统一 AI API 接入，支持国内直连、智能调度、会话保持、实时监控与按量计费。"
)

//go:embed all:dist
var frontendFS embed.FS

// PublicSettingsProvider is an interface to fetch public settings
type PublicSettingsProvider interface {
	GetPublicSettingsForInjection(ctx context.Context) (any, error)
}

// FrontendServer serves the embedded frontend with settings injection
type FrontendServer struct {
	distFS      fs.FS
	fileServer  http.Handler
	baseHTML    []byte
	cache       *HTMLCache
	settings    PublicSettingsProvider
	overrideDir string // local file override directory
}

// NewFrontendServer creates a new frontend server with settings injection
func NewFrontendServer(settingsProvider PublicSettingsProvider) (*FrontendServer, error) {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		return nil, err
	}

	// Read base HTML once
	file, err := distFS.Open("index.html")
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()

	baseHTML, err := io.ReadAll(file)
	if err != nil {
		return nil, err
	}

	cache := NewHTMLCache()
	cache.SetBaseHTML(baseHTML)

	return &FrontendServer{
		distFS:      distFS,
		fileServer:  http.FileServer(http.FS(distFS)),
		baseHTML:    baseHTML,
		cache:       cache,
		settings:    settingsProvider,
		overrideDir: filepath.Join("data", "public"),
	}, nil
}

// InvalidateCache invalidates the HTML cache (call when settings change)
func (s *FrontendServer) InvalidateCache() {
	if s != nil && s.cache != nil {
		s.cache.Invalidate()
	}
}

// Middleware returns the Gin middleware handler
func (s *FrontendServer) Middleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		path := c.Request.URL.Path

		// Skip API routes
		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		staticPath, staticFileExists := resolveEmbeddedStaticPath(s.distFS, cleanPath)

		// For index.html or SPA routes, serve with injected settings
		if cleanPath == "index.html" || !staticFileExists {
			applyFrontendIndexingHeader(c, path)
			s.serveIndexHTML(c)
			return
		}

		// Try local override first
		if s.tryServeOverride(c, staticPath) {
			return
		}

		// Serve static files normally (hashed assets get long-lived cache headers)
		applyStaticAssetCacheHeaders(c.Writer.Header(), staticPath)
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
	}
}

func resolveEmbeddedStaticPath(distFS fs.FS, cleanPath string) (string, bool) {
	candidates := []string{cleanPath}
	if strings.HasSuffix(cleanPath, "/") {
		candidates = []string{
			cleanPath + "index.html",
			strings.TrimSuffix(cleanPath, "/"),
		}
	}

	for _, candidate := range candidates {
		file, err := distFS.Open(candidate)
		if err != nil {
			continue
		}
		_ = file.Close()
		return candidate, true
	}

	return cleanPath, false
}

// tryServeOverride checks if a local override file exists and serves it.
// Files in overrideDir take precedence over embedded files.
func (s *FrontendServer) tryServeOverride(c *gin.Context, cleanPath string) bool {
	if s.overrideDir == "" {
		return false
	}
	filePath := filepath.Join(s.overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func (s *FrontendServer) serveIndexHTML(c *gin.Context) {
	// Get nonce from context (generated by SecurityHeaders middleware)
	nonce := middleware.GetNonceFromContext(c)

	// Check cache first
	cached := s.cache.Get()
	if cached != nil {
		// Check If-None-Match for 304 response
		if match := c.GetHeader("If-None-Match"); match == cached.ETag {
			c.Status(http.StatusNotModified)
			c.Abort()
			return
		}

		// Replace nonce placeholder with actual nonce before serving
		content := replaceNoncePlaceholder(cached.Content, nonce)

		c.Header("ETag", cached.ETag)
		c.Header("Cache-Control", "no-cache") // Must revalidate
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	// Cache miss - fetch settings and render
	ctx, cancel := context.WithTimeout(c.Request.Context(), 2*time.Second)
	defer cancel()

	settings, err := s.settings.GetPublicSettingsForInjection(ctx)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", replaceNoncePlaceholder(s.baseHTML, nonce))
		c.Abort()
		return
	}

	settingsJSON, err := json.Marshal(settings)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", replaceNoncePlaceholder(s.baseHTML, nonce))
		c.Abort()
		return
	}

	rendered := s.injectSettings(settingsJSON)
	s.cache.Set(rendered, settingsJSON)

	// Replace nonce placeholder with actual nonce before serving
	content := replaceNoncePlaceholder(rendered, nonce)

	cached = s.cache.Get()
	if cached != nil {
		c.Header("ETag", cached.ETag)
	}
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func (s *FrontendServer) injectSettings(settingsJSON []byte) []byte {
	// Create the script tag to inject with nonce placeholder
	// The placeholder will be replaced with actual nonce at request time
	script := []byte(`<script nonce="` + NonceHTMLPlaceholder + `">window.__APP_CONFIG__=` + string(settingsJSON) + `;</script>`)

	// Inject before </head>
	headClose := []byte("</head>")
	result := bytes.Replace(s.baseHTML, headClose, append(script, headClose...), 1)

	// Apply custom branding before the browser paints the static defaults.
	result = injectSiteMetadata(result, settingsJSON)
	result = injectSiteFavicon(result, settingsJSON)

	return result
}

type seoSettings struct {
	SiteName     string `json:"site_name"`
	SiteSubtitle string `json:"site_subtitle"`
}

func injectSiteMetadata(document, settingsJSON []byte) []byte {
	cfg := seoSettings{}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return document
	}

	siteName := strings.TrimSpace(cfg.SiteName)
	if siteName == "" {
		siteName = seoDefaultSiteName
	}
	description := strings.TrimSpace(cfg.SiteSubtitle)
	if description == "" {
		description = seoDefaultDescription
	}
	title := siteName + " - AI API 中转 | Claude、GPT、Gemini 多模型网关"

	document = replaceElementContent(document, "title", htmlpkg.EscapeString(title))
	document = replaceMetaContent(document, "name", "description", description)
	document = replaceMetaContent(document, "property", "og:site_name", siteName)
	document = replaceMetaContent(document, "property", "og:title", title)
	document = replaceMetaContent(document, "property", "og:description", description)
	document = replaceMetaContent(document, "name", "twitter:title", title)
	document = replaceMetaContent(document, "name", "twitter:description", description)
	return replaceStructuredData(document, siteName, description)
}

func replaceElementContent(document []byte, element, content string) []byte {
	open := []byte("<" + element + ">")
	close := []byte("</" + element + ">")
	start := bytes.Index(document, open)
	end := bytes.Index(document, close)
	if start == -1 || end == -1 || end < start {
		return document
	}
	end += len(close)
	replacement := []byte("<" + element + ">" + content + "</" + element + ">")
	return replaceByteRange(document, start, end, replacement)
}

func replaceMetaContent(document []byte, attribute, value, content string) []byte {
	needle := []byte(attribute + `="` + value + `"`)
	attributeIndex := bytes.Index(document, needle)
	if attributeIndex == -1 {
		return document
	}
	start := bytes.LastIndex(document[:attributeIndex], []byte("<meta"))
	if start == -1 {
		return document
	}
	endOffset := bytes.IndexByte(document[attributeIndex:], '>')
	if endOffset == -1 {
		return document
	}
	end := attributeIndex + endOffset + 1
	contentAttribute := []byte(`content="`)
	contentStartOffset := bytes.Index(document[start:end], contentAttribute)
	if contentStartOffset == -1 {
		return document
	}
	contentStart := start + contentStartOffset + len(contentAttribute)
	contentEndOffset := bytes.IndexByte(document[contentStart:end], '"')
	if contentEndOffset == -1 {
		return document
	}
	contentEnd := contentStart + contentEndOffset
	return replaceByteRange(document, contentStart, contentEnd, []byte(htmlpkg.EscapeString(content)))
}

func replaceStructuredData(document []byte, siteName, description string) []byte {
	needle := []byte(`<script id="site-structured-data"`)
	start := bytes.Index(document, needle)
	if start == -1 {
		return document
	}
	openEndOffset := bytes.IndexByte(document[start:], '>')
	if openEndOffset == -1 {
		return document
	}
	contentStart := start + openEndOffset + 1
	contentEndOffset := bytes.Index(document[contentStart:], []byte("</script>"))
	if contentEndOffset == -1 {
		return document
	}
	contentEnd := contentStart + contentEndOffset

	structuredData := map[string]any{
		"@context": "https://schema.org",
		"@graph": []any{
			map[string]any{
				"@type":       "WebSite",
				"@id":         seoSiteOrigin + "/#website",
				"url":         seoSiteOrigin + "/",
				"name":        siteName,
				"description": description,
				"inLanguage":  []string{"zh-CN", "en"},
			},
			map[string]any{
				"@type": "Organization",
				"@id":   seoSiteOrigin + "/#organization",
				"url":   seoSiteOrigin + "/",
				"name":  siteName,
				"logo":  seoSiteOrigin + "/logo.svg",
			},
			map[string]any{
				"@type":               "SoftwareApplication",
				"@id":                 seoSiteOrigin + "/#software",
				"url":                 seoSiteOrigin + "/",
				"name":                siteName,
				"applicationCategory": "DeveloperApplication",
				"operatingSystem":     "Web",
				"description":         description,
				"image":               seoShareImageURL,
			},
		},
	}
	payload, err := json.Marshal(structuredData)
	if err != nil {
		return document
	}
	return replaceByteRange(document, contentStart, contentEnd, payload)
}

func replaceByteRange(document []byte, start, end int, replacement []byte) []byte {
	result := make([]byte, 0, len(document)-(end-start)+len(replacement))
	result = append(result, document[:start]...)
	result = append(result, replacement...)
	result = append(result, document[end:]...)
	return result
}

// injectSiteFavicon replaces the static favicon with a configured, browser-safe image URL.
func injectSiteFavicon(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteLogo string `json:"site_logo"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return html
	}

	logoURL := safeImageURL(cfg.SiteLogo)
	if logoURL == "" {
		return html
	}

	linkStart := bytes.Index(html, []byte(`<link rel="icon"`))
	if linkStart == -1 {
		return html
	}
	linkEndOffset := bytes.IndexByte(html[linkStart:], '>')
	if linkEndOffset == -1 {
		return html
	}
	linkEnd := linkStart + linkEndOffset + 1
	replacement := []byte(`<link rel="icon" href="` + htmlpkg.EscapeString(logoURL) + `" />`)

	var buf bytes.Buffer
	buf.Write(html[:linkStart])
	buf.Write(replacement)
	buf.Write(html[linkEnd:])
	return buf.Bytes()
}

func safeImageURL(value string) string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return ""
	}
	if strings.HasPrefix(trimmed, "/") && !strings.HasPrefix(trimmed, "//") {
		return trimmed
	}
	if strings.HasPrefix(strings.ToLower(trimmed), "data:image/") {
		return trimmed
	}

	parsed, err := url.Parse(trimmed)
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" {
		return ""
	}
	return trimmed
}

// replaceNoncePlaceholder replaces the nonce placeholder with actual nonce value
func replaceNoncePlaceholder(html []byte, nonce string) []byte {
	return bytes.ReplaceAll(html, []byte(NonceHTMLPlaceholder), []byte(nonce))
}

// ServeEmbeddedFrontend returns a middleware for serving embedded frontend
// This is the legacy function for backward compatibility when no settings provider is available
func ServeEmbeddedFrontend() gin.HandlerFunc {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		panic("failed to get dist subdirectory: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(distFS))
	overrideDir := filepath.Join("data", "public")

	return func(c *gin.Context) {
		path := c.Request.URL.Path

		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		staticPath, staticFileExists := resolveEmbeddedStaticPath(distFS, cleanPath)
		if staticFileExists {
			if cleanPath == "index.html" {
				applyFrontendIndexingHeader(c, path)
			}
			// Try local override first
			if tryServeOverrideFile(c, overrideDir, staticPath) {
				return
			}
			applyStaticAssetCacheHeaders(c.Writer.Header(), staticPath)
			fileServer.ServeHTTP(c.Writer, c.Request)
			c.Abort()
			return
		}

		applyFrontendIndexingHeader(c, path)
		serveIndexHTML(c, distFS)
	}
}

// tryServeOverrideFile is a standalone version of tryServeOverride for legacy usage.
func tryServeOverrideFile(c *gin.Context, overrideDir, cleanPath string) bool {
	if overrideDir == "" {
		return false
	}
	filePath := filepath.Join(overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func shouldBypassEmbeddedFrontend(path string) bool {
	trimmed := strings.TrimSpace(path)
	return strings.HasPrefix(trimmed, "/api/") ||
		strings.HasPrefix(trimmed, "/v1/") ||
		strings.HasPrefix(trimmed, "/v1beta/") ||
		strings.HasPrefix(trimmed, "/backend-api/") ||
		strings.HasPrefix(trimmed, "/antigravity/") ||
		strings.HasPrefix(trimmed, "/setup/") ||
		trimmed == "/health" ||
		trimmed == "/models" ||
		trimmed == "/responses" ||
		strings.HasPrefix(trimmed, "/responses/") ||
		trimmed == "/alpha/search" ||
		strings.HasPrefix(trimmed, "/images/") ||
		strings.HasPrefix(trimmed, "/videos/")
}

func applyFrontendIndexingHeader(c *gin.Context, path string) {
	if !shouldIndexFrontendPath(path) {
		c.Header("X-Robots-Tag", frontendNoIndexValue)
	}
}

func shouldIndexFrontendPath(path string) bool {
	normalized := strings.TrimRight(strings.TrimSpace(path), "/")
	return normalized == "" || normalized == "/home"
}

func serveIndexHTML(c *gin.Context, fsys fs.FS) {
	file, err := fsys.Open("index.html")
	if err != nil {
		c.String(http.StatusNotFound, "Frontend not found")
		c.Abort()
		return
	}
	defer func() { _ = file.Close() }()

	content, err := io.ReadAll(file)
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to read index.html")
		c.Abort()
		return
	}

	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func HasEmbeddedFrontend() bool {
	_, err := frontendFS.ReadFile("dist/index.html")
	return err == nil
}
